/* COMPLETE
 * Even Fibonacci Numbers
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 *	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>
#define LIMIT 4000000

 int main(void){

 	unsigned long long sum;
 	int previous[2];
 	int next = 0;

 	/* Initialize the previous values to 1,1 */
 	previous[0] = 1;
 	previous[1] = 1;

 	/* Loop until the limit has been reached */
 	while(next <= LIMIT){

 		/* Add the value onto the sum if it is even */
 		if(next % 2 == 0) sum += next;

 		/* rotate the previous values to set up for the next iteration */
 		next = previous[0] + previous[1];
 		previous[0] = previous[1];
 		previous[1] = next;
 	}

 	printf("Sum of Even Fibonacci numbers: %llu\n", sum);

 	return 0;
 	
 }