/* 
 * Highly Divisble Triangular Number
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * Let us list the factors of the first seven triangle numbers:
 *
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

int main(void){
	unsigned long long curr_num = 1;
    unsigned long long sum;
    int num_divisors = 0;
    
    while (num_divisors < 500) {
        num_divisors = 0;
        sum = 0;
        unsigned long long i = curr_num;
        // Generate the traingular number
        for (; i > 0; i-- ) {
            sum += i;
        }
        
        // calculate divisors 1 by 1
        for (i = 1; i < sqrt(sum); i++) {
            if (curr_num % i == 0) {
                num_divisors++;
            }
        }
        
        curr_num++;
        printf("%llu : %d\n", sum, num_divisors);    
    }
    
    return 0;
}
