/* 
 * Highly Divisble Triangular Number
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * Let us list the factors of the first seven triangle numbers:
 *
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

int main(void){
	unsigned long long curr_num = 1;
    unsigned long long curr_sum = 0;
    int total_divisors = 0;
    
    while (total_divisors < 500) {
        total_divisors = 0;
        //sum = 0;
        unsigned long long i = curr_num;
        // Generate the traingular number
        curr_sum += curr_num;
        
        // Calculate prime divisors
        int num_divisors = 0;
        unsigned long long sum = curr_sum;
        unsigned long long curr_divisor = 2;
        while (sum > 1) {
            if (sum % curr_divisor == 0) {
                num_divisors++;
                sum /= curr_divisor;
            } else {
                curr_divisor++;
                if (num_divisors > 0) {
                    total_divisors = (total_divisors == 0) ? (num_divisors + 1) : total_divisors * (num_divisors + 1);
                    num_divisors = 0;
                }
            }
        }
        if (num_divisors > 0) {
            total_divisors = (total_divisors == 0) ? (num_divisors + 1) : total_divisors * (num_divisors + 1);
            num_divisors = 0;
        }
        curr_num++;
    }
    printf("Triangular Number: %llu, num divisors: %d\n", curr_sum, total_divisors); 
    
    return 0;
}
